format_version: 1.1.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - BITRISE_PROJECT_PATH: /Users/godrei/Develop/bitrise/sample-apps/sample-apps-android/build.gradle
  - GRADLE_TASK: assembleAndroidTest
  - GRADLEW_PATH: /Users/godrei/Develop/bitrise/sample-apps/sample-apps-android/gradlew
workflows:
  primary:
    steps:
    - git-clone@3.1.1: {}
    - gradle-runner@1.3.1:
        inputs:
        - gradle_file: $BITRISE_PROJECT_PATH
        - gradle_task: $GRADLE_TASK
        - gradlew_path: $GRADLEW_PATH
    - deploy-to-bitrise-io@1.2.2: {}
