format_version: 1.1.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
app:
  envs:
  - FASTLANE_LANE: test
workflows:
  primary:
    steps:
    - git-clone@3.1.1: {}
    - certificate-and-profile-installer@1.4.0: {}
    - fastlane@2.1.3:
        inputs:
        - lane: $FASTLANE_LANE
